// =========================================================
// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by the build/dev server (src/index.ts).
// =========================================================
import { lazy } from "react";
import type { Tool } from "./tools.index";

export interface EnrichedTool extends Tool {
  autoDetected?: boolean;
  filePath?: string;
}

export const tools: EnrichedTool[] = [
  {
    "id": "json-formatter",
    "name": "JSON Formatter",
    "description": "Paste raw JSON to format, validate, and explore it with syntax highlighting.",
    "type": "react",
    "path": "react/json-formatter",
    "category": "Developer",
    "tags": [
      "json",
      "format",
      "validate"
    ],
    "filePath": "react/json-formatter/index.tsx",
    "date": 1781117480014.8323
  },
  {
    "id": "word-counter",
    "name": "Word Counter",
    "description": "Counts words, characters, sentences, and reading time as you type.",
    "type": "react",
    "path": "react/word-counter",
    "category": "Text",
    "tags": [
      "text",
      "words",
      "reading"
    ],
    "filePath": "react/word-counter/index.tsx",
    "date": 1781117494223.3523
  },
  {
    "id": "gradient-maker",
    "name": "Gradient Maker",
    "description": "Build CSS gradients visually and copy the ready-to-use code.",
    "type": "html",
    "path": "html/gradient-maker",
    "category": "Design",
    "tags": [
      "css",
      "gradient",
      "color"
    ],
    "filePath": "html/gradient-maker/index.html",
    "date": 1781117579366.2617
  },
  {
    "id": "base64",
    "name": "Base64 Codec",
    "description": "Encode or decode Base64 strings instantly, with file support.",
    "type": "react",
    "path": "react/base64",
    "category": "Developer",
    "tags": [
      "encode",
      "decode",
      "base64"
    ],
    "filePath": "react/base64/index.tsx",
    "date": 1781117519776.1885
  },
  {
    "id": "color-picker",
    "name": "Color Picker",
    "description": "Convert between HEX, RGB, HSL, and OKLCH color formats.",
    "type": "html",
    "path": "html/color-picker",
    "category": "Design",
    "tags": [
      "color",
      "hex",
      "oklch"
    ],
    "filePath": "html/color-picker/index.html",
    "date": 1781117615555.541
  },
  {
    "id": "markdown-preview",
    "name": "Markdown Preview",
    "description": "Write Markdown on the left, see live rendered HTML on the right.",
    "type": "react",
    "path": "react/markdown-preview",
    "category": "Text",
    "tags": [
      "markdown",
      "preview",
      "md"
    ],
    "filePath": "react/markdown-preview/index.tsx",
    "date": 1781117547433.1296
  },
  {
    "id": "textarea",
    "name": "Textarea",
    "description": "",
    "type": "html",
    "path": "html/textarea",
    "category": "Text",
    "tags": [
      "html",
      "textarea"
    ],
    "autoDetected": true,
    "filePath": "html/textarea.html",
    "date": 1781254228825.6033
  },
  {
    "id": "pelangan-wifi",
    "name": "Pelangan Wifi",
    "description": "",
    "type": "html",
    "path": "html/pelangan-wifi",
    "category": "Utility",
    "tags": [
      "html",
      "pelangan-wifi"
    ],
    "autoDetected": true,
    "filePath": "html/pelangan-wifi/index.html",
    "date": 1781119020969.1487
  },
  {
    "id": "javasandi",
    "name": "Javasandi",
    "description": "",
    "type": "html",
    "path": "html/javasandi",
    "category": "Utility",
    "tags": [
      "html",
      "javasandi"
    ],
    "autoDetected": true,
    "filePath": "html/javasandi.html",
    "date": 1781118326188.6184
  },
  {
    "id": "javascript",
    "name": "Javascript",
    "description": "",
    "type": "html",
    "path": "html/javascript",
    "category": "Utility",
    "tags": [
      "html",
      "javascript"
    ],
    "autoDetected": true,
    "filePath": "html/javascript/index.html",
    "date": 1781118450889.0264
  },
  {
    "id": "paste_image",
    "name": "Paste Image",
    "description": "",
    "type": "react",
    "path": "react/paste_image",
    "category": "Utility",
    "tags": [
      "react",
      "paste_image"
    ],
    "autoDetected": true,
    "filePath": "react/paste_image.tsx",
    "date": 1781119243369.0012
  },
  {
    "id": "Pelangan-wifi",
    "name": "Pelangan Wifi",
    "description": "",
    "type": "react",
    "path": "react/Pelangan-wifi",
    "category": "Utility",
    "tags": [
      "react",
      "Pelangan-wifi"
    ],
    "autoDetected": true,
    "filePath": "react/Pelangan-wifi.tsx",
    "date": 1781119165710.2588
  }
];

export const reactComponents: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
  "react/json-formatter": lazy(() => import("./react/json-formatter/index.tsx")),
  "react/word-counter": lazy(() => import("./react/word-counter/index.tsx")),
  "react/base64": lazy(() => import("./react/base64/index.tsx")),
  "react/markdown-preview": lazy(() => import("./react/markdown-preview/index.tsx")),
  "react/paste_image": lazy(() => import("./react/paste_image.tsx")),
  "react/Pelangan-wifi": lazy(() => import("./react/Pelangan-wifi.tsx")),
};
